---
- hosts: all
  become: true
  tasks:

  - name: Install service SSHD
    apt:
      update_cache: yes
      cache_valid_time: 86400 # one day
      force_apt_get: yes
      name: openssh-server=1:7.6p1-4ubuntu0.5
      state: present
  
  - name: Start service SSHD, if not started
    service:
      name: sshd
      state: started
